export const FEATURE_RANGES = {
  'Guards': {
    'Age':            { min: 18,  max: 30,  defaultValue: 20 },
    'Height':         { min: 68,  max: 84,  defaultValue: 76 },   // inches
    'Weight':         { min: 140, max: 260, defaultValue: 190 },  // lbs
    'CT_Win%':        { min: 0,   max: 100,defaultValue: 50 },
    'CT_SOS':         { min: 0,   max: 10, defaultValue: 5   },
    'C_MPG':          { min: 0,   max: 40, defaultValue: 20  },
    'C_USG%':         { min: 0,   max: 100,defaultValue: 20  },
    'C_FG%':          { min: 0,   max: 100,defaultValue: 45  },
    'FGA_per_game':   { min: 0,   max: 30, defaultValue: 15  },
    'C_3P%':          { min: 0,   max: 100,defaultValue: 35  },
    '3PA_per_game':   { min: 0,   max: 15, defaultValue: 5   },
    'C_FT%':          { min: 0,   max: 100,defaultValue: 75  },
    'FTA_per_game':   { min: 0,   max: 15, defaultValue: 5   },
    'AST_per_game':   { min: 0,   max: 15, defaultValue: 5   },
    'STL_per_game':   { min: 0,   max: 5,  defaultValue: 1   },
    'TOV_per_game':   { min: 0,   max: 10, defaultValue: 3   },
    'PPG':            { min: 0,   max: 40, defaultValue: 15  },
    'OffReb':         { min: 0,   max: 15, defaultValue: 5   },
    'DefReb':         { min: 0,   max: 20, defaultValue: 8   },
    'C_OBPM':         { min: -5,  max: 5,  defaultValue: 0   },
    'C_PER':          { min: 0,  max: 30,  defaultValue: 15   }
  },

  'Wings': {
    'Age':            { min: 18,  max: 30, defaultValue: 21 },
    'Height':         { min: 72,  max: 88, defaultValue: 80 },
    'Weight':         { min: 150, max: 280,defaultValue: 215 },
    'CT_Win%':        { min: 0,   max: 100,defaultValue: 50 },
    'CT_SOS':         { min: 0,   max: 10, defaultValue: 5   },
    'C_MPG':          { min: 0,   max: 40, defaultValue: 25  },
    'C_USG%':         { min: 0,   max: 100,defaultValue: 20  },
    'C_FG%':          { min: 0,   max: 100,defaultValue: 45  },
    'FGA_per_game':   { min: 0,   max: 30, defaultValue: 12  },
    'C_3P%':          { min: 0,   max: 100,defaultValue: 35  },
    '3PA_per_game':   { min: 0,   max: 15, defaultValue: 4   },
    'C_FT%':          { min: 0,   max: 100,defaultValue: 70  },
    'FTA_per_game':   { min: 0,   max: 15, defaultValue: 4   },
    'AST_per_game':   { min: 0,   max: 10, defaultValue: 4   },
    'STL_per_game':   { min: 0,   max: 5,  defaultValue: 1   },
    'TOV_per_game':   { min: 0,   max: 10, defaultValue: 3   },
    'PPG':            { min: 0,   max: 40, defaultValue: 14  },
    'OffReb':         { min: 0,   max: 15, defaultValue: 6   },
    'DefReb':         { min: 0,   max: 20, defaultValue: 8   },
    'C_BPM':          { min: -5,  max: 5,  defaultValue: 0   },
    'C_PER':          { min: 0,  max: 30,  defaultValue: 15   }
  },

  'Bigs': {
    'Age':            { min: 18,  max: 32, defaultValue: 22 },
    'Height':         { min: 78,  max: 96, defaultValue: 84 },
    'Weight':         { min: 180, max: 320,defaultValue: 250 },
    'CT_Win%':        { min: 0,   max: 100,defaultValue: 50 },
    'CT_SOS':         { min: 0,   max: 10, defaultValue: 5   },
    'C_MPG':          { min: 0,   max: 40, defaultValue: 22  },
    'C_USG%':         { min: 0,   max: 100,defaultValue: 18  },
    'C_FG%':          { min: 0,   max: 100,defaultValue: 50  },
    'FGA_per_game':   { min: 0,   max: 30, defaultValue: 10  },
    'C_3P%':          { min: 0,   max: 100,defaultValue: 30  },
    '3PA_per_game':   { min: 0,   max: 15, defaultValue: 2   },
    'C_FT%':          { min: 0,   max: 100,defaultValue: 65  },
    'FTA_per_game':   { min: 0,   max: 15, defaultValue: 4   },
    'AST_per_game':   { min: 0,   max: 10, defaultValue: 3   },
    'STL_per_game':   { min: 0,   max: 5,  defaultValue: 0.5 },
    'TOV_per_game':   { min: 0,   max: 10, defaultValue: 3   },
    'PPG':            { min: 0,   max: 40, defaultValue: 12  },
    'OffReb':         { min: 0,   max: 15, defaultValue: 8   },
    'DefReb':         { min: 0,   max: 20, defaultValue: 12  },
    'BLK_per_game':   { min: 0,   max: 10, defaultValue: 2   },
    'C_DBPM':         { min: -5,  max: 5,  defaultValue: 0   },
    'C_PER':          { min: 0,  max: 30,  defaultValue: 15   }
  }
};
