export const FEATURE_RANGES = {
  Guards: {
    Age:            { min: 17, max: 24, defaultValue: 20 },
    Height:         { min: 68, max: 90, defaultValue: 74 },
    Weight:         { min: 150, max: 280, defaultValue: 185 },
    Wingspan:       { min: 68, max: 96, defaultValue: 76 },
    C_MPG:          { min: 0,  max: 40, defaultValue: 30 },
    FGA_per_game:   { min: 0,  max: 25, defaultValue: 15 },
    '3PA_per_game': { min: 0,  max: 15, defaultValue: 6 },
    'FTA_per_game': { min: 0,  max: 15, defaultValue: 5 },
    'C_FG%':        { min: 30, max: 80, defaultValue: 45 },
    'C_3P%':        { min: 15, max: 50, defaultValue: 40 },
    'C_FT%':        { min: 40, max: 95, defaultValue: 85 },
    PTS_per_game:   { min: 0,  max: 40, defaultValue: 20 },
    AST_per_game:   { min: 0,  max: 12, defaultValue: 6.5 },
    TOV_per_game:   { min: 0,  max: 8,  defaultValue: 2.5 },
    OffReb:         { min: 0,  max: 6,  defaultValue: 0.6 },
    DefReb:         { min: 0,  max: 15, defaultValue: 3 },
    STL_per_game:   { min: 0,  max: 6,  defaultValue: 2 },
    BLK_per_game:   { min: 0,  max: 6,  defaultValue: 0.3 },
    C_BPM:          { min: -15, max: 20, defaultValue: 12 }
  },

  Wings: {
    Age:            { min: 17, max: 24, defaultValue: 20 },
    Height:         { min: 68, max: 90, defaultValue: 79 },
    Weight:         { min: 150, max: 280, defaultValue: 220 },
    Wingspan:       { min: 68, max: 96, defaultValue: 81 },
    C_MPG:          { min: 0,  max: 40, defaultValue: 30 },
    FGA_per_game:   { min: 0,  max: 25, defaultValue: 16 },
    '3PA_per_game': { min: 0,  max: 15, defaultValue: 3 },
    'FTA_per_game': { min: 0,  max: 15, defaultValue: 7 },
    'C_FG%':        { min: 30, max: 80, defaultValue: 52 },
    'C_3P%':        { min: 15, max: 50, defaultValue: 37 },
    'C_FT%':        { min: 40, max: 95, defaultValue: 80 },
    PTS_per_game:   { min: 0,  max: 40, defaultValue: 18 },
    AST_per_game:   { min: 0,  max: 12, defaultValue: 4 },
    TOV_per_game:   { min: 0,  max: 8,  defaultValue: 2 },
    OffReb:         { min: 0,  max: 6,  defaultValue: 2.2 },
    DefReb:         { min: 0,  max: 15, defaultValue: 7.5 },
    STL_per_game:   { min: 0,  max: 6,  defaultValue: 1.5 },
    BLK_per_game:   { min: 0,  max: 6,  defaultValue: 1.5 },
    C_BPM:          { min: -15, max: 20, defaultValue: 12 }
  },

  Bigs: {
    Age:            { min: 17, max: 24, defaultValue: 20 },
    Height:         { min: 68, max: 90, defaultValue: 83 },
    Weight:         { min: 150, max: 280, defaultValue: 245 },
    Wingspan:       { min: 68, max: 96, defaultValue: 86 },
    C_MPG:          { min: 0,  max: 40, defaultValue: 30 },
    FGA_per_game:   { min: 0,  max: 25, defaultValue: 14 },
    '3PA_per_game': { min: 0,  max: 15, defaultValue: 1.5 },
    'FTA_per_game': { min: 0,  max: 15, defaultValue: 6 },
    'C_FG%':        { min: 30, max: 80, defaultValue: 65 },
    'C_3P%':        { min: 0,  max: 50, defaultValue: 28 },
    'C_FT%':        { min: 40, max: 95, defaultValue: 65 },
    PTS_per_game:   { min: 0,  max: 40, defaultValue: 16 },
    AST_per_game:   { min: 0,  max: 12, defaultValue: 2 },
    TOV_per_game:   { min: 0,  max: 8,  defaultValue: 2 },
    OffReb:         { min: 0,  max: 6,  defaultValue: 3.5 },
    DefReb:         { min: 0,  max: 15, defaultValue: 12 },
    STL_per_game:   { min: 0,  max: 6,  defaultValue: 1.5 },
    BLK_per_game:   { min: 0,  max: 6,  defaultValue: 4 },
    C_BPM:          { min: -15, max: 20, defaultValue: 12 }
  }
};
